drop database if exists proyecto_segunda_evaluacion;
create database proyecto_segunda_evaluacion;
use proyecto_segunda_evaluacion;
-- Users Table
CREATE TABLE USUARIO (
    DNI VARCHAR(9) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    CONTRASENIA VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255),
    DIRECCION VARCHAR(255),
    EMAIL VARCHAR(255),
    TELEFONO VARCHAR(15),
    TIPO_USUARIO TINYINT NOT NULL DEFAULT 0,
    CONSTRAINT PK_USUARIO PRIMARY KEY (DNI)
);

-- Products Table
CREATE TABLE PRODUCTO (
    ID INT AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL,
    PRECIO DECIMAL(10, 2) NOT NULL,
    DESCRIPCION VARCHAR(255),
    CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID)
);

-- Bookings Table
CREATE TABLE RESERVA (
    ID_RESERVA INT PRIMARY KEY,
    DNI_USUARIO VARCHAR(9),
    FECHA DATE,
	NUM_PERSONAS INT,
    ESTADO ENUM('pendiente', 'confirmada', 'cancelada') NOT NULL DEFAULT 'pendiente',
    FOREIGN KEY (DNI_USUARIO) REFERENCES USUARIO(DNI)
);

-- Cart Table
CREATE TABLE PEDIDO (
    DNI_USUARIO VARCHAR(9),
    ID_PRODUCTO INT,
    CANTIDAD INT,
    FECHA DATE,
    ESTADO ENUM('pendiente', 'confirmado', 'cancelado') NOT NULL DEFAULT 'pendiente',
    PRIMARY KEY (DNI_USUARIO, ID_PRODUCTO),
    FOREIGN KEY (DNI_USUARIO) REFERENCES USUARIO(DNI),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID)
);
